### ISSUE TITLE
Getting back url of opened view

### ISSUE THREAD

**Issue by alexeymakarov90** [EddyVerbruggen/cordova-plugin-safariviewcontroller#17]
Hi, having issues with oauth2: when you open a new window with an oauth link it will redirect you with GET params. How can we catch that 'get' params?
InAppBrowsers gets the reference of window and can controll it's redirects:
 var ref = window.open(urlWithParams, '_blank', 'location=no,clearcache=yes,clearsessioncache=yes');
                      ref.addEventListener('loadstart', function(event) {
                            if (event.url.indexOf(CONFIG.redirectUri) === 0) {
...

**Comment by cvillerm** [comment]
This is an old issue now, but, what such a safe way of web browsing, isn't the standard way to pass values back to the application by using a URL using a custom scheme? Did you try that? It is by design that the SafariViewController is exposing little information.

https://developer.pingidentity.com/en/resources/napps-native-app-sso.html describes an end-to-end flow illustrating that. The `redirect_uri` of the OAuth flow is based on such a custom scheme.
