### ISSUE TITLE
Event loaded and closed never get called

### ISSUE THREAD

**Issue by robertodias180** [EddyVerbruggen/cordova-plugin-safariviewcontroller#48]
These events never get called. Not sure what the problem is. 
This happen on both Android and iOS.

**Comment by Woutwo** [comment]
+1

**Comment by aedwards12** [comment]
+1

**Comment by zhougonglai** [comment]
+1
me too...

**Comment by sliard** [comment]
I think it's the same problem than #44 or #39 
With iOS 9 it's work well but not in iOS 10.2 if you set hidden=true

**Comment by magicfa** [comment]
I've debug the plugin and the reason is that the promise will be delivered once. Means the events will be send for all three events but first event, in this case 'opened', win the race. You can try to comment out the last three lines of the show function of SafariViewController.m.
If you do this the the event 'loaded' will win.

We should follow the request of Andrew to implement an event handler like in inAppBrowser.

**Comment by soramister** [comment]
Hello,

Any updates on this problem?

**Comment by EddyVerbruggen** [comment]
After `show` is called, the plugin keeps the callback [(this line)](https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/blob/0cdd110459b796b668d39b441143514e8752968b/src/ios/SafariViewController.m#L85) and when the `loaded` event is sent to your JS it is kept again [(this line)](https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/blob/0cdd110459b796b668d39b441143514e8752968b/src/ios/SafariViewController.m#L141).

Would be nice if someone not using a Promise wrapper for this plugin can confirm whether or not this is actually an issue.

**Comment by jwmann** [comment]
I'm also getting this issue.
Any updates?
