### ISSUE TITLE
Option to hide the address bar

### ISSUE THREAD

**Issue by DaveRand** [EddyVerbruggen/cordova-plugin-safariviewcontroller#66]
Great plugin!  I need an option to hide the address bar (if possible) like you can with the cordova-plugin-inappbrowser plugin. It will make things less confusing for users of my app. 

I would also like the ability to change the "Done" button label and an option that will insert a title string in the center of the title bar if the address bar is hidden.

Thank you

**Comment by simonwatt** [comment]
This is also exactly what I need. 

Hiding the address bar would be perfect, but if that isn't possible then at the least the ability to change the 'Done' text on iOS. I'm performing a login via Auth0, so after user enters login details they are likely to hit 'Done' and close the window instead of actually hitting the button to submit the form. It's not as bad on Android since they see X which would clearly be closing the window.

**Comment by Hirbod** [comment]
+1

**Comment by EddyVerbruggen** [comment]
Please reopen with a link to Apple's docs on how to achieve this. Perhaps one day the do..

**Comment by marcostadeusc** [comment]
Is it possible to do that? Or is something far away?
